"use client";
import {useEffect,useState} from 'react';
import type {Book} from '@/lib/types';
import type {PublishingItem,LinkStats} from '@/lib/publishing';
import {CopyField,SharePanel} from './ShareDialog';
const field='w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm text-white';
const button='rounded-lg border border-slate-700 px-4 py-2 text-sm text-white hover:border-brand-400 disabled:opacity-40';
type Kind='custom'|'track'|'shelf';
export default function PublishingPanel({kind,books}:{kind:Kind;books:Book[]}){
 const [now]=useState(()=>Date.now());
 const [items,setItems]=useState<PublishingItem[]>([]),[stats,setStats]=useState<Record<string,LinkStats>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [editing,setEditing]=useState<Partial<PublishingItem>|null>(null),[title,setTitle]=useState(''),[slug,setSlug]=useState(''),[book,setBook]=useState(''),[expires,setExpires]=useState(''),[selected,setSelected]=useState<string[]>([]),[description,setDescription]=useState(''),[color,setColor]=useState('#101521'),[sharing,setSharing]=useState<PublishingItem|null>(null);
 async function load(){setLoading(true);try{const r=await fetch('/api/publishing');const d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.items);setStats(d.stats);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{let alive=true;fetch('/api/publishing').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(alive){setItems(d.items);setStats(d.stats);}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[]);
 const labels={custom:'Custom links',track:'Trackable links',shelf:'Bookshelves'};
 const url=(i:PublishingItem)=>`${location.origin}/${i.kind==='custom'?'go/'+i.id.slice(7):i.kind==='track'?'t/'+i.id:'shelf/'+i.id}`;
 function edit(i?:PublishingItem){setEditing(i||{});setTitle(i?.data.title||'');setSlug(i?.kind==='custom'?i.id.slice(7):'');setBook(i?.data.book||books.find(b=>b.status==='ready')?.id||'');setExpires(i?.data.expires?.slice(0,10)||'');setSelected(i?.data.books||[]);setDescription(i?.data.description||'');setColor(i?.data.color||'#101521');setError('');}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/publishing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editing?.id,kind,title,slug,book,expires:expires?expires+'T23:59:59.999Z':undefined,books:selected,description,color,enabled:editing?.data?.enabled!==false})});const d=await r.json();if(!r.ok)throw Error(d.error);setEditing(null);await load();setSharing(d.item);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function toggle(i:PublishingItem){setBusy(true);try{const r=await fetch('/api/publishing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:i.id,kind:i.kind,...i.data,enabled:i.data.enabled===false})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="py-5"><div className="flex items-center justify-between gap-4"><div><h1 className="text-3xl font-semibold text-white">{labels[kind]}</h1><p className="mt-2 text-sm text-slate-400">{kind==='custom'?'Give each publication a memorable address.':kind==='track'?'Create a link for each campaign and see opens and pages reached.':'Curate ordered collections with their own shareable page.'}</p></div><button className={button} onClick={()=>edit()}>＋ Create {kind==='shelf'?'bookshelf':'link'}</button></div>
 {error&&<p role="alert" className="my-4 text-red-300">{error}</p>}
 {editing&&<form onSubmit={save} className="my-6 grid gap-4 rounded-xl border border-slate-700 bg-slate-900 p-5 sm:grid-cols-2"><label className="text-sm text-slate-300">Name<input required maxLength={160} className={field} value={title} onChange={e=>setTitle(e.target.value)} /></label>
 {kind==='custom'&&<label className="text-sm text-slate-300">Custom address: /go/<input required disabled={Boolean(editing.id)} pattern="[a-z0-9][a-z0-9-]{2,79}" placeholder="home-buyers-guide" className={field} value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())}/></label>}
 {kind!=='shelf'&&<label className="text-sm text-slate-300">Flipbook<select required className={field} value={book} onChange={e=>setBook(e.target.value)}><option value="">Choose a flipbook</option>{books.filter(b=>b.status==='ready').map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label>}
 {kind==='track'&&<label className="text-sm text-slate-300">Expiration (optional)<input type="date" className={field} value={expires} onChange={e=>setExpires(e.target.value)}/></label>}
 {kind==='shelf'&&<><label className="text-sm text-slate-300">Background<input type="color" className={field} value={color} onChange={e=>setColor(e.target.value)}/></label><label className="text-sm text-slate-300 sm:col-span-2">Description<textarea className={field} maxLength={500} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="sm:col-span-2"><p className="mb-3 text-sm text-slate-300">Choose publications, then set their order.</p>{books.filter(b=>b.status==='ready').map(b=><label key={b.id} className="mb-2 flex gap-3 text-sm text-slate-300"><input type="checkbox" checked={selected.includes(b.id)} onChange={e=>setSelected(e.target.checked?[...selected,b.id]:selected.filter(id=>id!==b.id))}/>{b.title}</label>)}<ol className="mt-4">{selected.map((id,n)=><li key={id} className="flex items-center gap-3 py-2 text-sm text-white"><span className="flex-1">{n+1}. {books.find(b=>b.id===id)?.title}</span><button type="button" disabled={n===0} className={button} aria-label={`Move ${books.find(b=>b.id===id)?.title} up`} onClick={()=>setSelected(v=>{const a=[...v];[a[n-1],a[n]]=[a[n],a[n-1]];return a;})}>↑</button><button type="button" disabled={n===selected.length-1} className={button} aria-label={`Move ${books.find(b=>b.id===id)?.title} down`} onClick={()=>setSelected(v=>{const a=[...v];[a[n+1],a[n]]=[a[n],a[n+1]];return a;})}>↓</button></li>)}</ol></div></>}
 <div className="flex gap-3 sm:col-span-2"><button disabled={busy} className={button}>{busy?'Saving…':'Save'}</button><button type="button" className={button} onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 <div className="mt-6 divide-y divide-slate-800 rounded-xl border border-slate-800">{loading?<p className="p-6 text-slate-400">Loading…</p>:items.filter(i=>i.kind===kind).length===0?<p className="p-10 text-center text-slate-400">Create your first {kind==='shelf'?'bookshelf':'link'} to get started.</p>:items.filter(i=>i.kind===kind).map(i=><article key={i.id} className="flex flex-wrap items-center gap-5 bg-slate-900/40 p-5"><div className="min-w-0 flex-1"><h2 className="font-medium text-white">{i.data.title}</h2><p className="mt-1 break-all text-xs text-slate-400">{url(i)}</p><p className="mt-2 text-xs text-slate-500">{i.data.enabled===false?'Disabled':i.data.expires&&Date.parse(i.data.expires)<=now?'Expired':'Active'}{kind==='track'&&` · ${stats[i.id]?.opens||0} opens · ${stats[i.id]?.pages||0} page events`}{kind==='shelf'&&` · ${i.data.books?.length||0} flipbooks`}</p></div><button className={button} onClick={()=>edit(i)}>Edit</button><button className={button} onClick={()=>setSharing(i)}>Share & QR</button><button disabled={busy} className={button} onClick={()=>toggle(i)}>{i.data.enabled===false?'Enable':'Disable'}</button></article>)}</div>
 {sharing&&<div role="dialog" aria-modal="true" aria-label="Share publishing link" className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-6"><div className="w-full max-w-xl rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="mb-6 flex justify-between text-white"><h2>{sharing.data.title}</h2><button onClick={()=>setSharing(null)} aria-label="Close sharing">✕</button></div><CopyField label="Shareable link" value={url(sharing)}/><SharePanel shareUrl={url(sharing)} title={sharing.data.title||'Flipbook'}/>{sharing.kind==='shelf'&&<CopyField label="Website embed" multiline value={`<iframe src="${url(sharing)}" width="100%" height="700" title="Bookshelf"></iframe>`}/>}</div></div>}
 </section>;
}
